# Generated by Django 5.2.11 on 2026-03-29 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_attendancerecord_location_attendancerecord_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='location',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='WorkSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_cutoff_time', models.TimeField(default='09:00:00')),
                ('off_days', models.JSONField(blank=True, default=list)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
