# Generated by Django 5.2.11 on 2026-03-25 05:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_adcampaign_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
